import { createStore } from "vuex";

export default createStore({
    state: {
        projectsStore: [
            {
                id: 1,
                tag: 'Ванная комната',
                title: 'Современная ванная',
                breadcrumbs: 'Декор / Планировка',
                favorite: false,
                description: 'Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur',
                img_item: require("@/assets/img/projects/project_1/img_1.jpeg"),
                img_details_1: require("@/assets/img/projects/project_1/img_details_1.jpeg"),
                img_details_2: require("@/assets/img/projects/project_1/img_details_2.jpeg"),
                img_details_3: require("@/assets/img/projects/project_1/img_details_3.jpeg"),
            },
            {
                id: 2,
                tag: 'Ванная комната',
                title: 'Современная ванная',
                breadcrumbs: 'Декор / Планировка',
                favorite: false,
                description: 'Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur',
                img_item: require("@/assets/img/projects/project_2/img_1.jpeg"),
                img_details_1: require("@/assets/img/projects/project_2/img_details_1.jpeg"),
                img_details_2: require("@/assets/img/projects/project_2/img_details_2.jpeg"),
                img_details_3: require("@/assets/img/projects/project_2/img_details_3.jpeg"),
            },
            {
                id: 3,
                tag: 'Спальня',
                title: 'Современная спальня',
                breadcrumbs: 'Декор / Планировка',
                favorite: false,
                description: 'Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur',
                img_item: require("@/assets/img/projects/project_3/img_1.jpeg"),
                img_details_1: require("@/assets/img/projects/project_1/img_details_1.jpeg"),
                img_details_2: require("@/assets/img/projects/project_1/img_details_2.jpeg"),
                img_details_3: require("@/assets/img/projects/project_1/img_details_3.jpeg"),
            },
            {
                id: 4,
                tag: 'Спальня',
                title: 'Современная спальня',
                breadcrumbs: 'Декор / Планировка',
                favorite: false,
                description: 'Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur',
                img_item: require("@/assets/img/projects/project_4/img_1.jpeg"),
                img_details_1: require("@/assets/img/projects/project_1/img_details_1.jpeg"),
                img_details_2: require("@/assets/img/projects/project_1/img_details_2.jpeg"),
                img_details_3: require("@/assets/img/projects/project_1/img_details_3.jpeg"),

            },
            {
                id: 5,
                tag: 'Кухня',
                title: 'Современная кухня',
                breadcrumbs: 'Декор / Планировка',
                favorite: false,
                description: 'Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur',
                img_item: require("@/assets/img/projects/project_5/img_1.jpeg"),
                img_details_1: require("@/assets/img/projects/project_1/img_details_1.jpeg"),
                img_details_2: require("@/assets/img/projects/project_1/img_details_2.jpeg"),
                img_details_3: require("@/assets/img/projects/project_1/img_details_3.jpeg"),

            },
            {
                id: 6,
                tag: 'Кухня',
                title: 'Современная кухня',
                breadcrumbs: 'Декор / Планировка',
                favorite: false,
                description: 'Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur',
                img_item: require("@/assets/img/projects/project_6/img_1.jpeg"),
                img_details_1: require("@/assets/img/projects/project_1/img_details_1.jpeg"),
                img_details_2: require("@/assets/img/projects/project_1/img_details_2.jpeg"),
                img_details_3: require("@/assets/img/projects/project_1/img_details_3.jpeg"),
            },
            {
                id: 7,
                tag: 'Гостинная',
                title: 'Современная гостинная',
                breadcrumbs: 'Декор / Планировка',
                favorite: false,
                description: 'Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur',
                img_item: require("@/assets/img/projects/project_7/img_1.jpeg"),
                img_details_1: require("@/assets/img/projects/project_1/img_details_1.jpeg"),
                img_details_2: require("@/assets/img/projects/project_1/img_details_2.jpeg"),
                img_details_3: require("@/assets/img/projects/project_1/img_details_3.jpeg"),
            },
            {
                id: 8,
                tag: 'Гостинная',
                title: 'Современная гостинная',
                breadcrumbs: 'Декор / Планировка',
                favorite: false,
                description: 'Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur',
                img_item: require("@/assets/img/projects/project_8/img_1.jpeg"),
                img_details_1: require("@/assets/img/projects/project_1/img_details_1.jpeg"),
                img_details_2: require("@/assets/img/projects/project_1/img_details_2.jpeg"),
                img_details_3: require("@/assets/img/projects/project_1/img_details_3.jpeg"),

            },
        ],
        postsStore: [
            {
                id: 1,
                title: 'Создадим лучший макет перепланировки',
                tag: 'Кухня',
                short_desc: 'Дизайн кухни',
                img_prewiev: require("@/assets/img/blog/post_1/img_prewiev.jpeg"),
                img_heading: require("@/assets/img/blog/post_1/img_heading.jpeg"),
                img_post: require("@/assets/img/blog/post_1/img_2.jpeg"),
                date: '1 Декабрь,2022',
                text_start: 'В своей статье от 1994-го года журнал «Before & After» отследил фразу «Lorem ipsum ...» до философского трактата Цицерона О пределах добра и зла, написанного в 45 году до нашей эры на латинском языке. В оригинале текст выглядит так «Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit ...», и переводится как «Нет никого, кто любил бы свою боль, кто искал бы ее и хотел бы чтобы она была у него. Потому что это боль...»',
                quote: 'Какая-то умная и красивая цитата',
                subtitle: 'Design sprints are great',
                text_end: 'В оригинале текст выглядит так «Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit ...», и переводится как «Нет никого, кто любил бы свою боль, кто искал бы ее и хотел бы чтобы она была у него. Потому что это боль...»',
            },
            {
                id: 2,
                title: 'Лучшая спальня для Вас',
                tag: 'Спальня',
                short_desc: 'Дизайн спальни',
                img_prewiev: require("@/assets/img/blog/post_2/img_prewiev.jpeg"),
                img_heading: require("@/assets/img/blog/post_2/img_heading.jpeg"),
                img_post: require("@/assets/img/blog/post_2/img_2.jpeg"),
                date: '2 Декабрь,2022',
                text_start: 'В своей статье от 1994-го года журнал «Before & After» отследил фразу «Lorem ipsum ...» до философского трактата Цицерона О пределах добра и зла, написанного в 45 году до нашей эры на латинском языке. В оригинале текст выглядит так «Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit ...», и переводится как «Нет никого, кто любил бы свою боль, кто искал бы ее и хотел бы чтобы она была у него. Потому что это боль...»',
                quote: 'Какая-то умная и красивая цитата',
                subtitle: 'Design sprints are great',
                text_end: 'В оригинале текст выглядит так «Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit ...», и переводится как «Нет никого, кто любил бы свою боль, кто искал бы ее и хотел бы чтобы она была у него. Потому что это боль...»',
            },
            {
                id: 3,
                title: 'Современная архитектура',
                tag: 'Архитектура',
                short_desc: 'Дизайн для жизни',
                img_prewiev: require("@/assets/img/blog/post_3/img_prewiev.jpeg"),
                img_heading: require("@/assets/img/blog/post_3/img_heading.jpeg"),
                img_post: require("@/assets/img/blog/post_3/img_2.jpeg"),
                date: '3 Декабрь,2022',
                text_start: 'В своей статье от 1994-го года журнал «Before & After» отследил фразу «Lorem ipsum ...» до философского трактата Цицерона О пределах добра и зла, написанного в 45 году до нашей эры на латинском языке. В оригинале текст выглядит так «Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit ...», и переводится как «Нет никого, кто любил бы свою боль, кто искал бы ее и хотел бы чтобы она была у него. Потому что это боль...»',
                quote: 'Какая-то умная и красивая цитата',
                subtitle: 'Design sprints are great',
                text: 'В оригинале текст выглядит так «Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...», и переводится как «Нет никого, кто любил бы свою боль, кто искал бы ее и хотел бы чтобы она была у него. Потому что',
                text_end: 'В оригинале текст выглядит так «Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit ...», и переводится как «Нет никого, кто любил бы свою боль, кто искал бы ее и хотел бы чтобы она была у него. Потому что это боль...»',
            },
            {
                id: 4,
                title: 'Создадим лучший макет перепланировки',
                tag: 'Кухня',
                short_desc: 'Дизайн кухни',
                img_prewiev: require("@/assets/img/blog/post_4/img_prewiev.jpeg"),
                img_heading: require("@/assets/img/blog/post_4/img_heading.jpeg"),
                img_post: require("@/assets/img/blog/post_4/img_2.jpeg"),
                date: '4 Декабрь,2022',
                text_start: 'В своей статье от 1994-го года журнал «Before & After» отследил фразу «Lorem ipsum ...» до философского трактата Цицерона О пределах добра и зла, написанного в 45 году до нашей эры на латинском языке. В оригинале текст выглядит так «Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit ...», и переводится как «Нет никого, кто любил бы свою боль, кто искал бы ее и хотел бы чтобы она была у него. Потому что это боль...»',
                quote: 'Какая-то умная и красивая цитата',
                subtitle: 'Design sprints are great',
                text_end: 'В оригинале текст выглядит так «Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit ...», и переводится как «Нет никого, кто любил бы свою боль, кто искал бы ее и хотел бы чтобы она была у него. Потому что это боль...»',
            },
            {
                id: 5,
                title: 'Лучшая спальня для Вас',
                tag: 'Спальня',
                short_desc: 'Дизайн спальни',
                img_prewiev: require("@/assets/img/blog/post_5/img_prewiev.jpeg"),
                img_heading: require("@/assets/img/blog/post_5/img_heading.jpeg"),
                img_post: require("@/assets/img/blog/post_5/img_2.jpeg"),
                date: '5 Декабрь,2022',
                text_start: 'В своей статье от 1994-го года журнал «Before & After» отследил фразу «Lorem ipsum ...» до философского трактата Цицерона О пределах добра и зла, написанного в 45 году до нашей эры на латинском языке. В оригинале текст выглядит так «Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit ...», и переводится как «Нет никого, кто любил бы свою боль, кто искал бы ее и хотел бы чтобы она была у него. Потому что это боль...»',
                quote: 'Какая-то умная и красивая цитата',
                subtitle: 'Design sprints are great',
                text_end: 'В оригинале текст выглядит так «Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit ...», и переводится как «Нет никого, кто любил бы свою боль, кто искал бы ее и хотел бы чтобы она была у него. Потому что это боль...»',
            },
            {
                id: 6,
                title: 'Современная архитектура',
                tag: 'Архитектура',
                short_desc: 'Дизайн для жизни',
                img_prewiev: require("@/assets/img/blog/post_6/img_prewiev.jpeg"),
                img_heading: require("@/assets/img/blog/post_6/img_heading.jpeg"),
                img_post: require("@/assets/img/blog/post_6/img_2.jpeg"),
                date: '6 Декабрь,2022',
                text_start: 'В своей статье от 1994-го года журнал «Before & After» отследил фразу «Lorem ipsum ...» до философского трактата Цицерона О пределах добра и зла, написанного в 45 году до нашей эры на латинском языке. В оригинале текст выглядит так «Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit ...», и переводится как «Нет никого, кто любил бы свою боль, кто искал бы ее и хотел бы чтобы она была у него. Потому что это боль...»',
                quote: 'Какая-то умная и красивая цитата',
                subtitle: 'Design sprints are great',
                text: 'В оригинале текст выглядит так «Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...», и переводится как «Нет никого, кто любил бы свою боль, кто искал бы ее и хотел бы чтобы она была у него. Потому что',
                text_end: 'В оригинале текст выглядит так «Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit ...», и переводится как «Нет никого, кто любил бы свою боль, кто искал бы ее и хотел бы чтобы она была у него. Потому что это боль...»',
            },
            {
                id: 7,
                title: 'Создадим лучший макет перепланировки',
                tag: 'Кухня',
                short_desc: 'Дизайн кухни',
                img_prewiev: require("@/assets/img/blog/post_1/img_prewiev.jpeg"),
                img_heading: require("@/assets/img/blog/post_1/img_heading.jpeg"),
                img_post: require("@/assets/img/blog/post_1/img_2.jpeg"),
                date: '7 Декабрь,2022',
                text_start: 'В своей статье от 1994-го года журнал «Before & After» отследил фразу «Lorem ipsum ...» до философского трактата Цицерона О пределах добра и зла, написанного в 45 году до нашей эры на латинском языке. В оригинале текст выглядит так «Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit ...», и переводится как «Нет никого, кто любил бы свою боль, кто искал бы ее и хотел бы чтобы она была у него. Потому что это боль...»',
                quote: 'Какая-то умная и красивая цитата',
                subtitle: 'Design sprints are great',
                text_end: 'В оригинале текст выглядит так «Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit ...», и переводится как «Нет никого, кто любил бы свою боль, кто искал бы ее и хотел бы чтобы она была у него. Потому что это боль...»',
            },
        ]
    },

    getters: {

    },
    mutations: {

    },
    actions: {

    },
    modules: {

    }
})